### ISSUE TITLE
ShapeNet normalization

### ISSUE THREAD

**Issue by jatentaki** [nv-tlabs/LION#10]
When you mention global normalization to [-1, 1] in table 1 and per-example normalization to [-1, 1] in table 2, which flags on [ShapeNet15kPointClouds](https://github.com/nv-tlabs/LION/blob/main/datasets/pointflow_datasets.py#L87) does that correspond to? I'm thinking about the combination of `normalize_per_shape`, `normalize_shape_box`, `normalize_std_per_axis` and `normalize_global`. Thank you.

**Comment by ZENGXH** [comment]
it's `normalize_shape_box`

**Comment by jatentaki** [comment]
Thank you for your answer. I assume `normalize_shape_box=True` refers to table 2, but what about table 1? Setting all the flags to False results in an exception coming from [here](https://github.com/nv-tlabs/LION/blob/main/datasets/pointflow_datasets.py#L238).

**Comment by ZENGXH** [comment]
yes. Table 1 using `normalize_global=True`.
