### ISSUE TITLE
1-NN accuracy benchmarking

### ISSUE THREAD

**Issue by jatentaki** [nv-tlabs/LION#11]
Are the numbers you report in tables 1 and 2 computed with [`compute_score`](https://github.com/nv-tlabs/LION/blob/031ccd75d62c052cb9df2652ef09298a862406e0/utils/eval_helper.py#L218) or some other code?

**Comment by ZENGXH** [comment]
yes it's computed with the `compute_score` function you link. examples can be found in https://github.com/nv-tlabs/LION/blob/main/script/compute_score.py
