### ISSUE TITLE
How to apply Shape Interpolation？

### ISSUE THREAD

**Issue by LiamTTT** [nv-tlabs/LION#13]
see title

**Comment by ZENGXH** [comment]
Hi, I add two scripts for interpolation: 
* `script/interpolate.sh`  interpolates in the prior sampling process; 
* `script/interpolate_posterior.sh` encodes two training point cloud to the latent space to get the posterior, compute the $z_T$ for the both shape, interpolate the shape and run the diffusion process: this can be used to interpolate two given shape. 

Hope it helps!
