### ISSUE TITLE
ShapeNet-vol dataset

### ISSUE THREAD

**Issue by Kitsunetic** [nv-tlabs/LION#14]
Could you share ShapeNet-vol dataset mentioned in Table 3 of paper?

![image](https://user-images.githubusercontent.com/14368796/215633758-f2bb2590-11ae-4582-8d91-31a1bfb0c55d.png)

**Comment by ZENGXH** [comment]
the dataset processing is similar to SAP. This [link](https://github.com/autonomousvision/shape_as_points#dataset-for-learning-based-reconstruction) and the link above should be helpful.
