### ISSUE TITLE
NAN Loss

### ISSUE THREAD

**Issue by fradino** [nv-tlabs/LION#22]
Hello,
I try to train the VAE, follow the step
![image](https://user-images.githubusercontent.com/31378961/220008523-54d5c3cb-cc27-48c4-9eac-d968d0e44ee4.png)
but the loss becomes NAN as follows
![微信图片_20230220122021](https://user-images.githubusercontent.com/31378961/220008811-0f12483b-2ebb-4600-b2c5-ec52bec4ac13.png)

**Comment by ZENGXH** [comment]
Let's discuss in the other thread (https://github.com/nv-tlabs/LION/issues/17#issue-1569715734)
