### ISSUE TITLE
training VAE

### ISSUE THREAD

**Issue by MariemOualha** [nv-tlabs/LION#23]
hello @ZENGXH , i'm trying to train VAE but i got  errors when i run the train_vae.sh 
 can you help me ! 
 ![Capture](https://user-images.githubusercontent.com/80748600/220080532-0fe6811c-d5a8-4595-995f-66f9bb22a3e0.PNG)

**Comment by ZENGXH** [comment]
Hi, I think there is a `$` symbol missing in line 13 somehow.

**Comment by albertotono** [comment]
How long did you train it? till epoch 8000?

**Comment by ZENGXH** [comment]
on 4 A100, it takes ~10 hours to train on airplane category for 8000 epochs, batch-size 32 per gpu.

**Comment by albertotono** [comment]
@MariemOualha for reference https://github.com/nv-tlabs/LION/issues/31
