### ISSUE TITLE
Did you tried to generating point with normal?

### ISSUE THREAD

**Issue by Kitsunetic** [nv-tlabs/LION#24]
@ZENGXH 

I'm just asking this out of curiosity.

Did you tried to generating point with normal?
I think it is much easier way to generate meshes by making LION generate point cloud with its normal `(N, 6)`.
Then it can build meshes by just applying DPSR directly instead of additionally fine-tuning SAP.

**Comment by ZENGXH** [comment]
yes I tried that before and it's able to generate reasonably good normal. 
One thing is that the fine-tuned SAP is more robust to the noise in the sampled points. If the normal is generated, it would still be better to fine-tune the following mesh reconstruction method to adapt to the noise (in points and normal) for better performance.
