### ISSUE TITLE
Per-category evaluation result of resampled pointcloud from fine-tuned SAP

### ISSUE THREAD

**Issue by Kitsunetic** [nv-tlabs/LION#25]
Thanks @ZENGXH for fast and detailed responses.

I want to ask is there per-category (airplane, chair, car) evaluation result of resampled pointcloud like table 15 of supp.

![image](https://user-images.githubusercontent.com/14368796/220857704-917ef8a4-2e24-468d-aecc-5920a8d9aff7.png)

**Comment by ZENGXH** [comment]
I have the results for 
* Airplane with `mixed`
![image](https://user-images.githubusercontent.com/12856437/220971795-7c55de25-859a-4e23-8e8f-3c6165e82e96.png)
* Airplane with `30 steps`  
![image](https://user-images.githubusercontent.com/12856437/220972103-972a3cd3-e5ee-406d-9a54-b5b3da06b67f.png)
* car with `mixed`
![image](https://user-images.githubusercontent.com/12856437/220972197-5583d038-444e-4b02-a1ce-e2e862d619ee.png)
* car with `30 steps`
![image](https://user-images.githubusercontent.com/12856437/220972404-a6d13df0-3c2b-440a-8212-89d813a27d89.png)
