### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by yunfan23** [nv-tlabs/LION#27]
Thanks for the impressive work. May I check with you how to generate the 3D visualization of the voxel shape and what about the point cloud shapes?

**Comment by ZENGXH** [comment]
I add the rendering code here: for point cloud  `utils/render_mitsuba_pc.py` (modified from https://github.com/zekunhao1995/PointFlowRenderer)  and for voxel `utils/render_voxel_cubes.py` (this one is basically hacking the mitsuba renderer a bit by putting a lot of voxels)

**Comment by JohanYe** [comment]
@ZENGXH I'm looking at the rendering code. In `utils/render_mitsuba_pc.py` and `utils/_render_voxel_cubes.py` they both call the function `main`. However no function such function is defined. Am i missing something mitsuba specific or is there a mistake?

**Comment by ZENGXH** [comment]
@JohanYe sorry for the confusion. You could check the function here, I am not calling the two scripts directly (so there is no `main` func, I just import it's plot function. 
* https://github.com/nv-tlabs/LION/blob/main/utils/render_mitsuba_pc.py#L319
* https://github.com/nv-tlabs/LION/blob/main/utils/render_voxel_cubes.py#L63

**Comment by JohanYe** [comment]
@ZENGXH Sorry for the late reply. I got it working with the help of your comment!  
Any chance you would share the mitsuba code for the mesh generation too?
