### ISSUE TITLE
Many-class 3D shape Generation Model

### ISSUE THREAD

**Issue by yuanzhen2020** [nv-tlabs/LION#35]
Hi @ZENGXH , thanks for your great work!
I want to train a many-class unconditional 3D shape generation model. Does this mean I need to use all classes of ShapeNet to train the VAE? I replaced "car" in the example with "all", but found that the loss became NAN at the beginning of training. How can I solve this problem?

**Comment by ZENGXH** [comment]
Using `data.normalize_global False data.normalize_shape_box True` in the args is better: I use the `shape_box` norm for model train on all class in the paper. And it seems to be more stable. I just upload the scripts: `scripts/train_vae_all.sh` with the arguments. You can try it.

**Comment by yuanzhen2020** [comment]
> Using `data.normalize_global False data.normalize_shape_box True` in the args is better: I use the `shape_box` norm for model train on all class in the paper. And it seems to be more stable. I just upload the scripts: `scripts/train_vae_all.sh` with the arguments. You can try it.

Thanks for your quick reply!

**Comment by yuanzhen2020** [comment]
Hi @ZENGXH, I found that train a multi-class VAE is very time-consuming (4 V100, batchsize = 24, ~1000 hours). Is there a way to speed up the training process?
