### ISSUE TITLE
MM-CD plot while training VAE

### ISSUE THREAD

**Issue by kakou34** [nv-tlabs/LION#41]
@ZENGXH  Hi, could you please share the plot of MM-CD of the VAE training for 1 class? 

Thanks in advance!

**Comment by ZENGXH** [comment]
this is the exp on car:
![image](https://user-images.githubusercontent.com/12856437/233710980-7cb65f78-6f87-4e50-82ca-b4daa12971ec.png)
chair:
![image](https://user-images.githubusercontent.com/12856437/233711137-fc1fdf16-ba5d-409e-a54c-1ed3a07836eb.png)
airplane:
![image](https://user-images.githubusercontent.com/12856437/233711209-4a8dceda-6edc-47b5-bb3c-448e2e5dd3ea.png)

**Comment by kakou34** [comment]
Thanks a lot!
