### ISSUE TITLE
Question about Diffuse-Denoise

### ISSUE THREAD

**Issue by Dekai21** [nv-tlabs/LION#49]
@ZENGXH Hi Xiaohui, thanks so much for your impressive work and code! I have a question about the Diffuse-Denoise process you mentioned in chapter 3.1 and app.c.1, which diffuses the latent feature (z0 and h0) to step τ < T and then denoises it back to get multimodal generation. The generation result in the paper is very fascinating, so I would like to how can I reproduce it with the released code? I try to look for this function but I still can't find it. ^^

**Comment by ZENGXH** [comment]
I upload this file: https://github.com/nv-tlabs/LION/blob/main/trainers/denoise_pts.py 
this trainer is written on top of the un-cleaned code base, so it may not runable with the current code. But you get some reference code here https://github.com/nv-tlabs/LION/blob/main/trainers/denoise_pts.py#L112-L121

**Comment by Dekai21** [comment]
@ZENGXH Thanks so much for your reply! ^^ I will have a look into this script, btw how many diffuse steps you would recommend for this diffuse-denoise procedure? I am doing some experiments on the car category, and I am quite interested on the appropriate steps on z0 and h0.

**Comment by ZENGXH** [comment]
I remember I try 50,100,150,200,250 before.
