### ISSUE TITLE
hey, I reimplement the encoder and diffusion process, but can not reach the metrics you report, when do you plan to release the training code?

### ISSUE THREAD

**Issue by hitsz-zuoqi** [nv-tlabs/LION#5]

**Comment by watarungurunnn** [comment]
@hitsz-zuoqi 
could you share the implemented code?

**Comment by hitsz-zuoqi** [comment]
> @hitsz-zuoqi could you share the implemented code?

Hey, I will share the code if I can fully reach the metrics. (in case of misleading)

**Comment by flamehaze1115** [comment]
@hitsz-zuoqi Hello, I am also trying to reproduce the repo. Maybe we could make WeChat friends and discuss this. My WeChat account is longxiao1115

**Comment by ZENGXH** [comment]
Hi, the code is released now. We will release the checkpoints and samples soon.
