### ISSUE TITLE
Can LION support various number of point instead of freezing the number to 2048

### ISSUE THREAD

**Issue by OswaldoBornemann** [nv-tlabs/LION#50]
Can LION support various number of point instead of freezing the number to 2048

**Comment by ZENGXH** [comment]
yes. You can set it through`data.tr_max_sample_points` and `data.te_max_sample_points`; 
* if the model is trained 2048, you can use different number of points in inference (I tried ~4k and it's working)
* you can also train the model with different number of points, I tried a much larger number before

**Comment by OswaldoBornemann** [comment]
@ZENGXH Thank you very much for your response. What I mean by "various number of point" here is that the number of points in each batch can vary. For example, there might be 2048 points in some batches and 1564 points in others. I've roughly identified the code for the decoder, and during the decoding process, I'm attempting to pass in a dynamically adjustable "num_points".
