### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by ardianumam** [nv-tlabs/LION#55]
Hi,

Thanks for the great work! Could you please provide the checkpoints for each shape categories?

Best,
Ardian

**Comment by ZENGXH** [comment]
it's released here https://huggingface.co/xiaohui2022/lion_ckpt

**Comment by ardianumam** [comment]
Hi,
Thanks for the reply. The link you provide gives an empty page (no model card) as shown in Figure 1 below. Do you mean ckpts are released [this link](https://huggingface.co/xiaohui2022/lion_ckpt/tree/main/unconditional)? I wonder if the provided ckpts in [the link](https://huggingface.co/xiaohui2022/lion_ckpt/tree/main/unconditional) are those SAP-finetuned LION so that if the generated clouds are used as SAP inputs, they can produce favorable mesh shapes. If not, could you release the SAP-finetuned checkpoints? 

Many thanks :)

Figure 1
![image](https://github.com/nv-tlabs/LION/assets/12822715/af744138-893c-4ace-83c1-99bb149ecd3e)

**Comment by yzhq97** [comment]
@ardianumam The models can be found in the "Files and versions" tab.
