### ISSUE TITLE
Trained checkpoints for all object classes.

### ISSUE THREAD

**Issue by yzhq97** [nv-tlabs/LION#56]
Thanks for sharing this great work. I notice that a script is provided for training the VAE on all object classes in ShapeNet, I wonder if a trained checkpoint can be provided for this model.

**Comment by ZENGXH** [comment]
added here: https://huggingface.co/xiaohui2022/lion_ckpt/tree/main/unconditional/all55

**Comment by yzhq97** [comment]
Thanks a lot!
