### ISSUE TITLE
DAE vs VAE examples of understanding h_0 and z_0

### ISSUE THREAD

**Issue by albertotono** [nv-tlabs/LION#59]
Could you kindly explain what DAE and VAE refer in your code specifically? 
![image](https://github.com/nv-tlabs/LION/assets/11828200/5e0452a6-6447-4e81-a99a-3f9c2e0c0c24)
Is the VAE the first diffusion and the DAE the 2nd one?

or in this case the VAE is the PVCNN?

**Comment by ZENGXH** [comment]
DAE refers to diffusion models in the latent space of vae (the two diffusion model in the right)
VAE refers to the encoder-decoder of the VAE
