### ISSUE TITLE
Where is the definition of the class_embedding function?

### ISSUE THREAD

**Issue by OswaldoBornemann** [nv-tlabs/LION#60]
Where is the definition of the class_embedding function?

**Comment by ZENGXH** [comment]
by default this function is not used, (cond_on_cat=False) if you want to add support for class embedding you could create a nn Embedding layer for it. 
the class conditioning support may not be completed in the code base, so there might be other places also requiring extra coding.

**Comment by OswaldoBornemann** [comment]
Thank you!
