### ISSUE TITLE
typo or ?

### ISSUE THREAD

**Issue by OswaldoBornemann** [nv-tlabs/LION#61]
I think the `DAE[0]` is related to the diffusion of `shape latent`, and the `DAE[1]` is related to the diffusion of `latent point`, which should be the local prior. So why the comment in the code which points to the `DAE[1]` is `global prior`?

https://github.com/nv-tlabs/LION/blob/b16212120e90742c62dbb8151560a56bbff8e53b/trainers/train_2prior.py#L422

**Comment by ZENGXH** [comment]
good catch! You are right. I fix the comment.
