### ISSUE TITLE
Why there are some grammar errors in the code？

### ISSUE THREAD

**Issue by Philcalab** [nv-tlabs/LION#64]
@ZENGXH , hello，thank you for providing the code. But there semms some grammar errors in the code and I don't how to modify them. If you  can give me some guidance. I wil geatly appreciate it. The following is two examples.
![1](https://github.com/nv-tlabs/LION/assets/117132650/5df94e8e-9d11-4072-a7b2-6461ccf7274b)
![2](https://github.com/nv-tlabs/LION/assets/117132650/f61447ca-4458-4f33-ab90-4104fad91983)

**Comment by ZENGXH** [comment]
it seems the text editor didn't find the function itself (the `sample_normal_jit` function is defined, but somehow it says unresolved reference). But the code should still be runnable.

**Comment by Philcalab** [comment]
> text

Thank you so much. And I wanna know what the util should be in my first image. Because there semms two directories or files named util. Could you tell me which one should be here?

**Comment by Philcalab** [comment]
@ZENGXH Thank you so much. And I wanna know what the util should be in my first image. Because there semms two directories or files named util. Could you tell me which one should be here?

**Comment by ZENGXH** [comment]
it's here: https://github.com/nv-tlabs/LION/blob/main/utils/utils.py

**Comment by Philcalab** [comment]
> it's here: https://github.com/nv-tlabs/LION/blob/main/utils/utils.py

thank you so much
