### ISSUE TITLE
Visualization code for diffusion process figure

### ISSUE THREAD

**Issue by khokao** [nv-tlabs/LION#69]
Hi @ZENGXH

I am so impressed by the attached visual diffusion process figure!
Could you please provide some example codes to replicate it?

<img width="272" alt="Screenshot 2024-04-22 at 21 38 31" src="https://github.com/nv-tlabs/LION/assets/86301305/d3487697-9e79-4e28-8d2f-3890da89223e">

**Comment by ZENGXH** [comment]
Please see this reply for the details of the visualization: https://github.com/NVlabs/LSGM/issues/12#issuecomment-1694122338 
Thanks!

**Comment by khokao** [comment]
Thanks a lot!
